kbst/terraform-kubestack

quickstart/Pipfile.lock
quickstart/src/ci-cd/Dockerfile

https://nvd.nist.gov/vuln/detail/CVE-2019-10906

Update Jinja2 to fix CVE-2019-10906

---

common/cluster_services/kubectl_apply.sh

with macOS I got this error in the moment I try to run
```
terraform workspace new ops
terraform apply
```
```
module.kind_zero.module.cluster.module.cluster_services.null_resource.cluster_services: Provisioning with 'local-exec'...
module.kind_zero.module.cluster.module.cluster_services.null_resource.cluster_services (local-exec): Executing: ["/bin/sh" "-c" "/Users/nullck/Documents/YARA/kubestack_local/infra-quickstart-kind/.terraform/modules/d00e427fa228231462c4208b4986c053/kubectl_apply.sh /Users/nullck/Documents/YARA/kubestack_local/infra-quickstart-kind/clusters/testing-ops-localhost.kind.infra.local/cluster_services.yaml"]
module.kind_zero.module.cluster.module.cluster_services.null_resource.cluster_services (local-exec): base64: invalid option -- d …
```

enabling macos to exec kubectl_apply

---

aws/_modules/eks/aws_iam_authenticator.tf
aws/_modules/eks/variables.tf
aws/cluster/configuration.tf
aws/cluster/main.tf

Allow users to configure aws-iam-authenticator by adding
variables to allow adding entries to mapRols, mapUsers and
mapAccounts.
Here's an example of how to use this in the config.auto.tfvars:
```
cluster_aws_auth_map_roles = <<MAPROLES
- roleARN: arn:aws:iam::000000000000:role/KubernetesAdmin
username: kubernetes-admin
groups:
- system:masters
MAPROLES
```
```
cluster_aws_auth_map_users = <<MAPUSERS
- userARN: arn:aws:iam::000000000000:user/Alice
username: alice
groups:
- system:masters
MAPUSERS
```
```
cluster_aws_auth_map_accounts = <<MAPACCOUNTS
- "012345678901"
- "456789012345"
MAPACCOUNTS
```

EKS: Allow configuring mapRoles, mapUsers and mapAccounts fix #68

---

quickstart/src/ci-cd/Dockerfile

The quickstart docker image build fails when compiling azure cli due to missing libffi. This PR adds missing library to Dockefile.

Add libffi to fix azure cli build

---

aws/_modules/eks/node_pool.tf
aws/_modules/eks/node_pool/main.tf
aws/_modules/eks/node_pool/variables.tf

Using the `eks_node_group` resource the configmap is created by AWS.
This causes an error because it already exists, when the kubernetes
provider tries to create it.
To allow framework users to modify the configmap to control `mapRoles`,
`mapAccounts` and `mapUsers` this commit makes the node_pool module
depend on the configmap.

EKS: Force node_pool to depend on aws-auth configmap

---

kind/cluster/configuration.tf

I had some problems with installing prometheus-operator with Kubernetes in Docker in version 1.16.1. A similar issue was reported here https://github.com/helm/charts/issues/17511. 
This could be fixed with upgrading the docker kind image to version v1.16.9.

Update kindest/node docker image to v1.16.9

---

aws/cluster/configuration.tf
azurerm/cluster/configuration.tf
azurerm/cluster/variables.tf
common/configuration/outputs.tf
common/configuration/variables.tf
common/configuration/versions.tf
google/cluster/configuration.tf
google/cluster/variables.tf
kind/cluster/configuration.tf
kind/cluster/variables.tf

This commit moves the implementation of the configuration
inheritance into a shared module and extends it to support
two commonly requested use-cases.
1. Support for custom names instead of apps and ops, fix #126
2. Support for more than two infrastructure environments
The module expects two input variables, `configuration` and
`base_key`.
`configuration` is a map of maps, and `base_key` sets the key
in the configuration map that all other keys will inherit from.
So, with the frameworks default apps and ops inheritance and
configuration, it has the exact same behavior as before. Ops
inherits from apps and overwrites values.
But given a Terraform configuration with different and more keys:
```
locals {
cfg = {
"a" = {
"a" = "a"
"b" = null
}
"b" = {
"b" = "b"
}
"c" = {
"c" = "c"
}
}
} …
```

Extend configuration inheritance implementation

---

azurerm/_modules/aks/ingress.tf
azurerm/_modules/aks/service_principal.tf
azurerm/_modules/aks/variables.tf
azurerm/cluster/configuration.tf
azurerm/cluster/main.tf
azurerm/cluster/providers.tf

* Starting with `v2.14.0` the provider talks to a new AKS API
which enforces a min. of 2 cpu cores and 4GB memory for nodes.
This commit updates the default vm_size. Configurations that
relied on this default, will see a destroy and recreate TF plan.
To avoid this, explicitly set the previous default for existing
clusters.
* Azure introduced Standard and Basic SKUs for loadbalancers
and public IPs. The SKUs of loadbalancers and IPs have to
match. By default public IPs are Basic and loadbalancers
created by Kubernetes are Standard. This commit changes
the IPs created by Terraform to use the Standard SKU.
Changing the SKU forces a new IP.

Update azurerm provider and fix breaking changes

---

aws/cluster/output.tf
google/cluster/output.tf
kind/cluster/output.tf

In PR #135, we had a discussion about adding outputs to the Kubestack `cluster` module. This PR adds an output containing the merged configuration for the current workspace. This should allow users to more easily extend Kubestack projects with additional resources, and to manage configuration variables for those additional resources using the same inheritance behavior as the rest of Kubestack.

Add current_config output to all providers

---

google/_modules/gke/cluster.tf
google/_modules/gke/variables.tf
google/cluster/configuration.tf
google/cluster/main.tf

By default GKE assigns an IP address to every node that it spins up, this in itself is not a problem however unless requested a Google Cloud Project has Quotas on the amount of Public IP's a project can have (I believe the default is 8). Therefore if you are not careful your cluster can not scale or do rolling updates do to insufficient IP's 
- Adds the ability to have private endpoints in the Google Kubernetes Cluster

Added private endpoint option to GKE setup

---

kind/_modules/kind/variables.tf
quickstart/src/configurations/aks/config.auto.tfvars
quickstart/src/configurations/eks/config.auto.tfvars
quickstart/src/configurations/gke/config.auto.tfvars
quickstart/src/configurations/kind/config.auto.tfvars
quickstart/src/configurations/multi-cloud/config.auto.tfvars

Remove some whitespace, fix spelling errors
The following snippet seems contradictory:
```
variable "metadata_fqdn" {
type        = string
description = "DNS name of the zone. Requires dot at the end. E.g. example.com"
}
```
Should this be
```
DNS name of the zone. Requires dot at the end. E.g. example.com.  # <- with trailing dot
```
or
```
DNS name of the zone. E.g. example.com  # <- without trailing dot
```
?
Some search results suggest that the dot is actually appended elsewhere:
```
google/_modules/gke/ingress.tf:	  dns_name = "${var.metadata_fqdn}."
aws/_modules/eks/ingress.tf:	  name = "${var.metadata_fqdn}."
```

Typo fixes

---

.gitignore
aws/_modules/eks/openid_connect.tf
aws/_modules/eks/variables.tf
aws/_modules/eks/versions.tf
aws/cluster/configuration.tf
aws/cluster/main.tf
azurerm/_modules/aks/main.tf
azurerm/_modules/aks/service_principal.tf
azurerm/_modules/aks/variables.tf
azurerm/cluster/configuration.tf
azurerm/cluster/main.tf
google/_modules/gke/cluster.tf
google/_modules/gke/node_pool.tf
google/_modules/gke/node_pool/main.tf
google/_modules/gke/node_pool/variables.tf
google/_modules/gke/variables.tf
google/cluster/configuration.tf
google/cluster/main.tf
quickstart/src/configurations/aks/clusters.tf

This PR implements the cluster side requirements for the Google and AWS solutions to natively integrate K8s workloads with Cloud IAM.
The first alternatives, relying on node roles has the problem that permissions are inherited by any workload on the node. While storing credentials in K8s secrets allows controlling permissions per workload it makes it, like shared credentials in general, difficult to rotate when team members join and leave.
The AKS equivalent feature, pod-managed identities, is only available in preview and not exposed through the Terraform provider yet. As such it was not implemented. The PR however includes changes to switch from the manually maintained service principal to the new managed identity feature. Both because that change is long overdue and also because it …

Integrate K8s workloads into Cloud IAM

---

azurerm/_modules/aks/main.tf
azurerm/_modules/aks/variables.tf
azurerm/cluster/configuration.tf
azurerm/cluster/main.tf

Quickly searching did not find anything similar on either google or EKS for the `sku_tier`, so just added this one.
Also forward the already present and similarly used (at least in EKS) `var.metadata_labels` to populate default pool `node_labels`

AKS: SKU tier and node_labels to default_pool

---

azurerm/_modules/aks/main.tf

This reverts commit 170bf26f3fb403c50d0613432cc6ca30ee49c89b, because adding
the node_labels to the default node pool requires a destroy and re-create on
the AKS cluster.
This is likely due to the node_pool using the legacy `default_node_pool`
block of the `azurerm_kubernetes_cluster` resource. Must migrate to using
a `azurerm_kubernetes_cluster_node_pool`. Will tackle this as part of
revamping node pools support in general.
Opening an issue to track this:
https://github.com/kbst/terraform-kubestack/issues/172

Revert "Re-use the metadata_labels variable for node_labels"

---

azurerm/_modules/aks/variables.tf
azurerm/_modules/aks/vnet.tf
azurerm/cluster/configuration.tf
azurerm/cluster/main.tf
tests/config.auto.tfvars

The vnet name did not use the metadata_name var, and the code
used to generate the name did only include the workspace.
This meant it supported multiple environments in the same Azure
resource group, but not multiple clusters per environment in
the same resource group.
With this commit, the vnet uses the metadata_name variable and
the subnet will include the name of the node pool.
Since changing the vnet and subnet names would require a
destroy and re-create plan, existing users can keep the old
names by setting `legacy_vnet_name = true`.

Fix AKS vnet names #170

---

common/configuration/outputs.tf

The [change to support maps of objects][1], not just maps of strings, introduced a regression. Keys not set in the base environment, but set in an environment that inherits from base were lost.
Previously ops inherited from apps and could overwrite values set in apps as well as add new key value pairs to the ops env.
This commit fixes the regression by looping through a set of all keys from both the environments to be merged.
[1]: https://github.com/kbst/terraform-kubestack/commit/22b0eb8c9439d8f4f2480c04f59acfeba54e6be9

Fix configuration module inheritance #176

---

oci/Dockerfile

Caching to a registry image requires running the build in a
container using buildkit. To be able to run the image and
copy the artifacts out of the container using docker cp
the image needs to be exported from the build container to
the host.
This additional build stage means, the image that is exported
to the host is much smaller by not including the Python and
Terraform caches.

Speed up dist with smaller dist-helper stage

---

oci/Dockerfile

In response to a potential disclosure of sensitive information
via the Codecov security incident, Hashicorp has rotated the
key used to sign providers. This commit updates Terraform to
v0.15.1 which uses the new key for validation.
More information: https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512

Update Terraform version to v0.15.1

---

aws/_modules/eks/master.tf
aws/_modules/eks/variables.tf
aws/cluster/configuration.tf
aws/cluster/main.tf

Signed-off-by: Spazzy <brendankamp757@gmail.com>
- Gives the ability to set the version of the EKS cluster
- Defaults to the latest version if no version is specified
Fix: https://github.com/kbst/terraform-kubestack/issues/164

Added ability to set cluster version on EKS

---

aws/_modules/eks/openid_connect.tf
aws/_modules/eks/provider.tf
aws/_modules/eks/roles_master.tf
aws/_modules/eks/roles_worker.tf

With the AWS partition fixed to 'aws', you will get errors about policy resources not
being found if you are in other partitions such as aws-cn or aws-us-gov. This replaces
the hard-coded partition with the actual partition so that policy ARNs have the right
parameters.

Generalize for different AWS partitions

---

google/_modules/gke/service_account.tf

Signed-off-by: Spazzy <brendankamp757@gmail.com>
- added a substring that will limit the name of the service account to 30 characters, (google requires names to match this regexp `^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])`)
fixes: https://github.com/kbst/terraform-kubestack/issues/145

Added limit for service account name GKE

---

azurerm/_modules/aks/main.tf
azurerm/_modules/aks/variables.tf
azurerm/cluster/configuration.tf
azurerm/cluster/main.tf

After experimenting with enabling the azure policy agent on a kubestack-built cluster, we found that kubestack was triggering a rebuild on every apply in an attempt to remove the `azure_policy` block.
This PR adds that block, along with a configuration parameter to allow users to enable the policy agent in their cluster module by adding
`enable_azure_policy_agent = true`
Omitting it will still add the `azure_policy` block, but with a default value of `false`

added configurable azure policy agent

---

google/_modules/gke/network.tf
google/_modules/gke/variables.tf
google/cluster/configuration.tf
google/cluster/main.tf

Signed-off-by: Spazzy <brendan@pento.io>
- adds ability to set the value `cloud_nat_enable_endpoint_independent_mapping`
- adds ability to set  the value `cloud_nat_min_ports_per_vm`
Both values default to Google defaults by setting them to null
Fixes: https://github.com/kbst/terraform-kubestack/issues/212

GKE: adds ability to set endpoint independent mapping to nat gateway

---

aws/_modules/eks/node_pool.tf
aws/_modules/eks/variables.tf
aws/_modules/eks/vpc.tf
aws/cluster/configuration.tf
aws/cluster/main.tf

* use /24 per AZ for control plane only
* use /20 per AZ for node pool
* users can configure both
* existing clusters share /24 per AZ across
control plane and nodes, `cluster_vpc_legacy_node_subnets`
is available to keep control plane subnets shared with
node pool for backwards compatibility

EKS: Default to separate control and node pool subnets

---

google/_modules/gke/node_pool.tf

This PR adds the missing `preemptible`, `auto_upgrade` and `upgrade` arguments to gke node_poll.

GKE: Fixing missed node_pool args

---

google/_modules/gke/network.tf
google/_modules/gke/variables.tf
google/cluster/configuration.tf
google/cluster/main.tf

Signed-off-by: Spazzy <brendan@pento.io>
* Adds variable `cloud_nat_ip_count` which changes the NAT gateway to create external IP addresses and attach them Manually to the Nat gateway instead of the NAT automatically creating it.
* If `cluster_nat_ip_count` it will default to using `AUTO_ONLY`
fixes:  https://github.com/kbst/terraform-kubestack/issues/218

adds manual IP addresses to the NAT gateway

---

aws/cluster/elb-dns/ingress.tf
aws/cluster/elb-dns/variables.tf

I'm running istio and changing the ingress from classic ELB to NLB. This breaks this module, as `aws_elb_hosted_zone_id` doesn't support NLB: https://github.com/hashicorp/terraform-provider-aws/issues/7988
This PR implements the workaround described in the issue with an optional flag.
We could also just use the workaround for all cases, but it seems to me that `aws_lb` doesn't support classic ELBs: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb

Add support for NLBs to AWS Ingress

---

azurerm/_modules/aks/main.tf
azurerm/_modules/aks/variables.tf
azurerm/cluster/configuration.tf
azurerm/cluster/main.tf

By default, the default AKS node pool (marked as `System`) is still available to run application code, which can have various negative consequences regarding resource drain.
To prevent that, [AKS system pods tolerate](https://docs.microsoft.com/en-us/azure/aks/use-system-pools#system-and-user-node-pools) `CriticalAddonsOnly=true:NoSchedule` taint, and the terraform provider [exposes](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#only_critical_addons_enabled) a bool option for adding this. This simply exposes that same option through the `kubestack` module.
Alternative would be adding this same taint manually afterwards, however with autoscaling new nodes would be created without taints, and the default node pool does not expose other …

AKS: Expose only critical addons taint option for default nodepool

---

aws/_modules/eks/master.tf
aws/_modules/eks/variables.tf
aws/cluster/configuration.tf
aws/cluster/main.tf

Expose cluster endpoint access configuration options to enable restricting network access to the k8s API endpoint.
Based on: https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html#modify-endpoint-access using https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#vpc_config-arguments
With extra effort on keeping `public_access_cidrs` as `null` if it's not set. This is in order to keep the current behavior if the parameter is not specified:
> EKS defaults this to a list with 0.0.0.0/0. **Terraform will only perform drift detection of its value when present in a configuration.**

Expose cluster endpoint access configuration options to enable restricting network access to the k8s API endpoint

---

google/_modules/gke/cluster.tf
google/_modules/gke/variables.tf
google/cluster/configuration.tf
google/cluster/main.tf

Similar work than https://github.com/kbst/terraform-kubestack/pull/234/ but for GKE. Based on 
- https://cloud.google.com/kubernetes-engine/docs/concepts/private-cluster-concept
- https://cloud.google.com/kubernetes-engine/docs/how-to/authorized-networks
- using: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#master_authorized_networks_config
Based [on the docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#master_authorized_networks_config):
> master_authorized_networks_config - (Optional) The desired configuration options for master authorized networks. Omit the nested `cidr_blocks` attribute to disallow external access (except the cluster node IPs, which GKE automatically whitelists). …

Expose master_authorized_networks_config option to enable restricting network access to the k8s API endpoint

---

azurerm/cluster/providers.tf
quickstart/src/configurations/aks/aks_zero_providers.tf
quickstart/src/configurations/multi-cloud/aks_zero_providers.tf
tests/aks_zero_providers.tf

In module provider configurations are discouraged. The AKS cluster
module still had a left-over provider configuration to set
`features {}` for the azurerm provider.
This commit moves this out of the cluster module into the root
module for both the generated starters and tests/.

AKS: Remove in-cluster-module provider configuration

---

azurerm/_modules/aks/main.tf
azurerm/_modules/aks/variables.tf
azurerm/cluster/configuration.tf
azurerm/cluster/main.tf

Exposes [this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#automatic_channel_upgrade) option. Defaults to `"none"`, which is the silent default anyway

AKS: enable automatic cluster upgrades

---

azurerm/_modules/aks/variables.tf
azurerm/cluster/configuration.tf

@to266 the tests fail with `Error: expected automatic_channel_upgrade to be one of [patch rapid stable node-image], got none`. I tried to fix this by making the default null. This way Kubestack/Terraform doesn't handle the attribute and will leave it to AKS to default to something. Your variable can still be used to select a specific channel.
Do you think that's the right approach or would you suggest to make e.g. `stable` the default channel?

AKS: Fix invalid automatic_channel_upgrade value none

---

quickstart/src/configurations/eks/eks_zero_ingress.tf
quickstart/src/configurations/multi-cloud/eks_zero_ingress.tf
tests/eks_zero_ingress.tf

The depends_on propagates to the data sources in the module
and causes the Route53 zone data source to only be read on
apply. This means the zone_id referenced in the Route53 host
resources will be in known-after-apply, which causes the
hosts to be recreated unnecessarily. Since this would cause
small time windows where uncached DNS queries would fail,
not having the explicit depends_on is the better compromise.
Even if it adds another reason why --target apply is required
during bootstrap or recreation.

EKS: Remove depends_on from eks_zero_dns_zone

---

azurerm/_modules/aks/main.tf
azurerm/_modules/aks/variables.tf
azurerm/cluster/configuration.tf
azurerm/cluster/main.tf

https://github.com/kbst/terraform-kubestack/issues/252
Adds the option to set availability_zones. Defaults to None which is what the module did previously.

Add azure aks default node pool availability_zones

---

.github/workflows/main.yml
Makefile
oci/Dockerfile

This PR adds a feature to sign the images that are generated using cosign (https://github.com/sigstore/cosign) and a keyless approach where it generates an ephemeral auth token to use during the signing process
the approach here is that we sign the staging image and when we promote that we carry over the image + the signature to avoid signing it again.
after this, I will work to sign the artifacts as well

sign the images and promote signed images

---

.github/workflows/main.yml

follow up PR to add the signing process to the blobs using cosign, it signs the zip files and pushes the signature file + the certificate file that can be used to validate the blob
/assign @pst

sign blobs with cosign

---

aws/_modules/eks/variables.tf
aws/_modules/eks/vpc.tf
aws/cluster/configuration.tf
aws/cluster/main.tf

Allow passing DNS hostnames/support boolean from AWS cluster module.
Fixes #214

AWS: Enable setting of VPC DNS hostnames/support

---

aws/cluster/configuration.tf

Currently `enabled_cluster_log_types`  variable by default enables logging for all EKS components in Cloudwatch. With these changes we can:
Disable EKS logging completely: 
```
enabled_cluster_log_types = ""
```
Selectively enable logging for EKS Controlplane components:
```
enabled_cluster_log_types  = "<use command separated from available options>"
e.g. enabled_cluster_log_types  = "audit" ## This would enable only audit logging for EKS and send logs to Cloudwatch
```

EKS Logging feature optional or disable it completely

---

google/_modules/gke/cluster.tf
google/_modules/gke/variables.tf
google/cluster/configuration.tf
google/cluster/main.tf

Allow enabling of [intranode visibility](https://cloud.google.com/kubernetes-engine/docs/how-to/intranode-visibility) for cluster

GKE: Enable specifying of intranode visibility for cluster

---

google/_modules/gke/cluster.tf
google/_modules/gke/variables.tf
google/cluster/configuration.tf
google/cluster/main.tf

Enable cluster database encryption as per [doc](https://cloud.google.com/kubernetes-engine/docs/how-to/encrypting-secrets)

GKE: Enable specifying of Cloud KSM key name for cluster database encryption

---

aws/_modules/eks/master.tf
aws/_modules/eks/variables.tf
aws/cluster/configuration.tf
aws/cluster/main.tf

Enable cluster encryption as per [docs](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html#enable-kms)

EKS: Enable specifying of KMS arn for cluster encryption

---

google/_modules/gke/network.tf
google/_modules/gke/variables.tf
google/cluster/configuration.tf
google/cluster/main.tf

Adds support for Cloud Router BGP advertisement configuration.
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router#bgp

GKE Cloud Router: support BGP router advertise config

---

aws/cluster/node-pool/configuration.tf
aws/cluster/node-pool/data_sources.tf

Fixes deprecation warning on `aws_subnet_ids`. Change to [aws_subnets](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnets)
<details>
<summary>Example</summary>
```terraform
Warning: Deprecated Resource
with module.my_app.data.aws_subnet_ids.current,
on .terraform/modules/eks_apne1_one_node_pool_machine_learning/aws/cluster/node-pool/data_sources.tf line 16, in data "aws_subnet_ids" "current":
16: data "aws_subnet_ids" "current" {
The aws_subnet_ids data source has been deprecated and will be removed in a
future version. Use the aws_subnets data source instead.
```
</details>

EKS: Fix deprecation warning for aws_subnet_ids

---

google/_modules/gke/cluster.tf
google/_modules/gke/variables.tf
google/cluster/configuration.tf
google/cluster/main.tf

Adds support for setting `logging_config` configuration block.
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#logging_config

GKE: add support for logging_config

---

azurerm/cluster/configuration.tf
azurerm/cluster/main.tf

(disclaimer: haven't yet tested if this does what I want, but seems pretty straightforward, so PR'ing immediately)
The intrinsic need is to allow customizing / adding additional labels/tags on AKS resources managed by kubestack. For example, adding various tags as required by [Vanta](https://help.vanta.com/hc/en-us/articles/9270488281492-Bulk-Tags) (`VantaOwner` and similar)

Allow passing additional labels/tags to AKS clusters

---

google/_modules/gke/cluster.tf
google/cluster/configuration.tf

False causes a rolling update of existing cluster
control planes, just because it explicitly sets
it to false.
Default null prevents that by allowing to make
the add-on block conditional.

Fix gcs fuse csi default false to null

---

aws/_modules/eks/master.tf
aws/_modules/eks/variables.tf
aws/cluster/configuration.tf
aws/cluster/main.tf

Allows configuring the EKS parameter `kubernetes_network_config.service_ipv4_cidr` for EKS users.

EKS: Allow configuring Service CIDR

---

.github/workflows/main.yml
aws/_modules/eks/node_pool/launch_template.tf
aws/_modules/eks/vpc.tf
azurerm/_modules/aks/service_principal.tf
google/_modules/gke/node_pool/main.tf
google/_modules/gke/node_pool/variables.tf
google/cluster/node-pool/configuration.tf
google/cluster/node-pool/main.tf
google/cluster/node-pool/variables.tf

* aws_vpc replace vpc with domain attribute
* azuread_service_principal rename application_id to client_id
* gke node_config refactor taints to be in block format

Fix deprecated attributes in new provider versions

---

google/_modules/gke/cluster.tf
google/_modules/gke/variables.tf
google/cluster/configuration.tf
google/cluster/main.tf
tests/gke_zero_cluster.tf

Starting with provider version 5, GKE requires deletion protection to be applied as false explicitly. Otherwise a destroy of the cluster will fail.

Allow setting GKE cluster deletion protection

---

google/_modules/gke/cluster.tf
google/_modules/gke/variables.tf
google/cluster/configuration.tf
google/cluster/main.tf

Add support for [maintenance exclusions](https://cloud.google.com/kubernetes-engine/docs/concepts/maintenance-windows-and-exclusions#exclusions) for GKE clusters.

GKE: Add support for maintenance exclusions
